name: CI/CD Pipeline - Build, Test and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t hello-app-test .

  test:
    name: Run Health Check
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run container in background
        run: |
          docker build -t hello-app-test .
          docker run -d -p 8000:8000 --name test-container hello-app-test
          sleep 5

      - name: Test /health endpoint
        run: |
          curl --fail http://localhost:8000/health
          
      - name: Cleanup
        run: |
          docker stop test-container
          docker rm test-container

  deploy:
    name: Deploy to Remote VM
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "."
          target: "~/hello-deploy"

      - name: Run docker-compose on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/hello-deploy
            docker-compose down
            docker-compose up -d --build
